# Generated by Django 5.0.6 on 2024-06-13 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_category_alter_booktable_email_alter_booktable_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
