# Generated by Django 5.0.6 on 2024-06-13 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_alter_menuitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={},
        ),
    ]
