# Generated by Django 5.0.6 on 2024-06-13 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_rename_product_desription_menuitem_item_desription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='item_desription',
            new_name='item_description',
        ),
    ]
